language: cpp
sudo: false

matrix:
  include:
    #============================================================
    #
    #                         Debug 
    #
    #============================================================
    #==============================
    #
    #          osx g++ 
    #
    #==============================

    - os: osx
      osx_image: xcode7.3
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode8
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode8.3
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.1
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.2
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.3
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.4
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode10
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Debug

    #==============================
    #
    #          osx clang++
    #
    #==============================

    - os: osx
      osx_image: xcode7.3
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode8
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode8.3
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.1
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.2
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.3
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode9.4
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode10
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Debug
    
    #============================================================
    #
    #                         Release 
    #
    #============================================================
    #==============================
    #
    #          osx g++ 
    #
    #==============================

    - os: osx
      osx_image: xcode7.3
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode8
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode8.3
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.1
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.2
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.3
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.4
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    - os: osx
      osx_image: xcode10
      compiler: g++
      env: CXX=g++ CC=gcc BUILD_TYPE=Release

    #==============================
    #
    #          osx clang++ 
    #
    #==============================

    - os: osx
      osx_image: xcode7.3
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode8
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode8.3
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.1
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.2
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.3
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode9.4
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

    - os: osx
      osx_image: xcode10
      compiler: clang++
      env: CXX=clang++ CC=clang BUILD_TYPE=Release

before_install:
  - eval

before_script:
  - cd ..
  - mkdir build
  - cd build
  - cmake ../Benchmark -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CC_COMPILER=${CC}

script:
  - make

after_script:
  - Benchmark/Benchmark